"use client";
const socials=[
  ["PlayStation","Neikosgamer#1489",null,"PS"],["Epic Games","foxgodneikos",null,"EP"],["Epic Games","ne1kosgamer",null,"EP"],
  ["GitHub","neikosfox95","https://github.com/neikosfox95","GH"],["Instagram","neikosgamer","https://instagram.com/neikosgamer","IG"],
  ["PlayStation","FoxKingNeko",null,"PS"],["Roblox","richgodofroblox96","https://www.roblox.com/users/profile?username=richgodofroblox96","RB"],
  ["Twitch","neikosgamer","https://twitch.tv/neikosgamer","TW"],["X","Foxkingneikos","https://x.com/Foxkingneikos","X"],
  ["X","neikosgamer2","https://x.com/neikosgamer2","X"],["Xbox","neikosgamer2",null,"XB"],
  ["YouTube","Neikos Gamer 2","https://www.youtube.com/results?search_query=Neikos+Gamer+2","YT"],["YouTube","Neikos Gamer","https://www.youtube.com/results?search_query=Neikos+Gamer","YT"],
] as const;
export default function AboutPage(){return <main className="about-page"><nav className="about-nav"><a href="/" className="about-brand"><span className="fox-idle">🦊</span><b>NEKO HUB</b></a><a href="/">Return to dashboard →</a></nav><section className="about-hero"><div className="about-orbit" aria-hidden="true"><i></i><i></i><i></i><span className="fox-idle">🦊</span></div><div><small>THE INTELLIGENCE LAYER FOR YOUR LOCKER</small><h1>Every cosmetic.<br/><em>One smarter hub.</em></h1><p>Neko Hub turns Fortnite&apos;s growing cosmetic universe into something personal: a place to discover items, build collections, watch the shop, and create loadouts that feel like you.</p><div className="about-actions"><a href="/">Explore Neko Hub</a><a href="#founder">Meet Neikos</a></div></div></section><section className="about-values"><article><b>LIVE</b><h2>Catalog intelligence</h2><p>Cosmetics are organized across outfits, back blings, pickaxes, gliders, emotes, wraps, and more.</p></article><article><b>YOURS</b><h2>Personal discovery</h2><p>Collections, wishlists, and shuffle tools turn a huge catalog into meaningful choices.</p></article><article><b>NEXT</b><h2>Built to evolve</h2><p>Neko Hub is designed as a lasting Fortnite companion—not another disposable item grid.</p></article></section><section className="founder" id="founder"><div className="founder-copy"><small>FOUNDER &amp; CEO</small><h2>Built by <em>Neikos.</em></h2><p>A creator, collector, and gamer building a cleaner way to understand the Fortnite ecosystem. Neko Hub brings together the tools he wanted in one focused, futuristic experience.</p><blockquote>“Know your collection. Discover what&apos;s next. Make every locker your own.”</blockquote></div><div className="founder-card"><div className="founder-avatar fox-idle">🦊</div><div><small>NEKO HUB / CREATOR PROFILE</small><h3>Neikos</h3><p>Founder · CEO · Community builder</p></div><span>ONLINE</span></div></section><section className="social-section"><div><small>FIND NEIKOS</small><h2>Across the ecosystem.</h2><p>Official creator and gaming profiles.</p></div><div className="social-grid">{socials.map(([platform,handle,url,icon])=>{const content=<><i>{icon}</i><span><small>{platform}</small><b>{handle}</b></span><em>{url?"↗":"COPY"}</em></>;return url?<a key={`${platform}-${handle}`} href={url} target="_blank" rel="noreferrer">{content}</a>:<button key={`${platform}-${handle}`} title={`Copy ${handle}`}>{content}</button>})}</div></section><footer><span className="fox-idle">🦊</span><b>NEKO HUB</b><p>Fortnite intelligence, sharpened.</p></footer></main>}
